ALTER TABLE tracks ADD COLUMN IF NOT EXISTS album_image_url TEXT NOT NULL DEFAULT '';
ALTER TABLE spotify_playlists ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '';
ALTER TABLE spotify_playlists ADD COLUMN IF NOT EXISTS track_count INTEGER NOT NULL DEFAULT 0;
