package spotify

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"time"
)

type Client struct {
	ClientID   string
	APIBase    string
	OAuth      OAuth
	Store      TokenStore
	HTTPClient *http.Client
	mu         sync.Mutex
}

func (c *Client) CurrentUserPlaylists(ctx context.Context) ([]Playlist, error) {
	playlists := []Playlist{}
	for offset := 0; ; offset += 50 {
		var page userPlaylistsPage
		if err := c.get(ctx, "/me/playlists?limit=50&offset="+strconv.Itoa(offset), &page); err != nil {
			return nil, err
		}
		for _, item := range page.Items {
			if item.ID == "" {
				continue
			}
			imageURL := ""
			if len(item.Images) > 0 {
				imageURL = item.Images[len(item.Images)-1].URL
			}
			trackCount := item.Items.Total
			if trackCount == 0 {
				trackCount = item.Tracks.Total
			}
			playlists = append(playlists, Playlist{ID: item.ID, Name: item.Name, Kind: "source", ImageURL: imageURL, TrackCount: trackCount})
		}
		if page.Next == "" || len(playlists) >= page.Total || len(page.Items) == 0 {
			break
		}
	}
	return playlists, nil
}

func (c *Client) PlaylistItems(ctx context.Context, playlist Playlist) ([]SyncedTrack, error) {
	items := []SyncedTrack{}
	for offset := 0; ; offset += 50 {
		path := "/playlists/" + url.PathEscape(playlist.ID) + "/items?limit=50&offset=" + strconv.Itoa(offset)
		var page playlistPage
		if err := c.get(ctx, path, &page); err != nil {
			return nil, err
		}
		for index, item := range page.Items {
			if item.Item.Type == "track" && item.Item.ID != "" {
				items = append(items, SyncedTrack{Playlist: playlist, Position: offset + index, AddedAt: item.AddedAt, Track: item.Item})
			}
		}
		if page.Next == "" || len(items) >= page.Total {
			break
		}
	}
	return items, nil
}

func (c *Client) TrackAudioFeatures(ctx context.Context, trackID string) (AudioFeatures, error) {
	var result AudioFeatures
	if trackID == "" {
		return result, fmt.Errorf("Spotify track ID is required")
	}
	if err := c.get(ctx, "/audio-features/"+url.PathEscape(trackID), &result); err != nil {
		return result, err
	}
	return result, nil
}

// TrackISRCs resolves recording identities in batches. ISRC is the stable seam
// used to map a Spotify-sourced Cueflow track to the same recording on TIDAL.
func (c *Client) TrackISRCs(ctx context.Context, trackIDs []string) (map[string]string, error) {
	result := make(map[string]string, len(trackIDs))
	for start := 0; start < len(trackIDs); start += 50 {
		end := min(start+50, len(trackIDs))
		ids := make([]string, 0, end-start)
		for _, id := range trackIDs[start:end] {
			id = strings.TrimSpace(id)
			if id == "" {
				return nil, fmt.Errorf("Spotify track ID is required")
			}
			ids = append(ids, id)
		}
		var response tracksResponse
		if err := c.get(ctx, "/tracks?ids="+url.QueryEscape(strings.Join(ids, ",")), &response); err != nil {
			return nil, err
		}
		for _, track := range response.Tracks {
			if track.ID != "" && track.ExternalIDs.ISRC != "" {
				result[track.ID] = track.ExternalIDs.ISRC
			}
		}
	}
	return result, nil
}

func (c *Client) Connected() bool {
	token, err := c.Store.Load()
	return err == nil && token.RefreshToken != ""
}

func (c *Client) PublishSet(ctx context.Context, name string, uris []string) (Playlist, error) {
	if !strings.HasPrefix(name, "Set Lab — ") {
		return Playlist{}, fmt.Errorf("draft playlist name must begin with %q", "Set Lab — ")
	}
	if len(uris) == 0 {
		return Playlist{}, fmt.Errorf("draft has no Spotify tracks to publish")
	}
	var created struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	}
	if err := c.sendJSON(ctx, http.MethodPost, "/me/playlists", map[string]any{
		"name": name, "public": false, "description": "Generated by Cueflow Set Lab. Permanent crates remain untouched.",
	}, &created); err != nil {
		return Playlist{}, err
	}
	if created.ID == "" {
		return Playlist{}, fmt.Errorf("Spotify created a playlist without an ID")
	}
	for start := 0; start < len(uris); start += 100 {
		end := min(start+100, len(uris))
		if err := c.sendJSON(ctx, http.MethodPost, "/playlists/"+url.PathEscape(created.ID)+"/items", map[string]any{"uris": uris[start:end]}, nil); err != nil {
			return Playlist{}, err
		}
	}
	return Playlist{ID: created.ID, Name: created.Name, Kind: "draft", Writable: true}, nil
}

func (c *Client) get(ctx context.Context, path string, target any) error {
	token, err := c.accessToken(ctx)
	if err != nil {
		return err
	}
	request, _ := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimRight(c.apiBase(), "/")+path, nil)
	request.Header.Set("Authorization", "Bearer "+token)
	response, err := c.client().Do(request)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if response.StatusCode/100 != 2 {
		return fmt.Errorf("Spotify API %s failed (%d)", path, response.StatusCode)
	}
	return json.NewDecoder(response.Body).Decode(target)
}

func (c *Client) sendJSON(ctx context.Context, method, path string, body any, target any) error {
	token, err := c.accessToken(ctx)
	if err != nil {
		return err
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return err
	}
	request, _ := http.NewRequestWithContext(ctx, method, strings.TrimRight(c.apiBase(), "/")+path, bytes.NewReader(payload))
	request.Header.Set("Authorization", "Bearer "+token)
	request.Header.Set("Content-Type", "application/json")
	response, err := c.client().Do(request)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if response.StatusCode/100 != 2 {
		return fmt.Errorf("Spotify API %s %s failed (%d)", method, path, response.StatusCode)
	}
	if target != nil {
		return json.NewDecoder(response.Body).Decode(target)
	}
	return nil
}

func (c *Client) accessToken(ctx context.Context) (string, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	token, err := c.Store.Load()
	if err != nil {
		return "", fmt.Errorf("Spotify is not connected: %w", err)
	}
	if token.AccessToken != "" && time.Now().Before(token.ExpiresAt) {
		return token.AccessToken, nil
	}
	refreshed, err := c.OAuth.Refresh(ctx, token.RefreshToken)
	if err != nil {
		return "", err
	}
	if err := c.Store.Save(refreshed); err != nil {
		return "", err
	}
	return refreshed.AccessToken, nil
}

func (c *Client) apiBase() string {
	if c.APIBase != "" {
		return c.APIBase
	}
	return "https://api.spotify.com/v1"
}
func (c *Client) client() *http.Client {
	if c.HTTPClient != nil {
		return c.HTTPClient
	}
	return &http.Client{Timeout: 20 * time.Second}
}
