import { expect, test } from '@playwright/test'

test('generates, compares, and inspects persisted set variations', async ({ page, request }) => {
  await request.post('http://127.0.0.1:8787/api/seed')
  await page.goto('/')
  await expect(page.getByText('Find the sequence')).toBeVisible()
  await expect(page.getByText(/tracks ready/)).toBeVisible()
  await page.getByRole('button', { name: 'Generate set variations' }).click()
  await expect(page.getByText('Afro to pressure — A')).toBeVisible()
  await expect(page.getByRole('tab')).toHaveCount(3)
  const timeline = page.getByLabel(/mix timeline/i)
  await expect(timeline).toBeVisible()
  const tracks = timeline.getByRole('button')
  expect(await tracks.count()).toBeGreaterThanOrEqual(3)
  await timeline.getByRole('button', { name: /^2\./ }).click()
  const inspector = page.getByLabel('Track and transition inspector')
  await expect(inspector).toContainText('CUE 02')
  await expect(inspector).toContainText('Transition in')
  await expect(inspector).toContainText('Tempo')
  await page.getByRole('tab').nth(1).click()
  await expect(page.getByText('Afro to pressure — B')).toBeVisible()
})
