// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {tidal} from '../models';
import {spotify} from '../models';

export function Bootstrap():Promise<domain.Bootstrap>;

export function ConnectSpotify():Promise<void>;

export function ConnectTidal():Promise<void>;

export function EnrichTrack(arg1:domain.TrackEnrichment):Promise<void>;

export function GenerateSets(arg1:domain.GenerateRequest):Promise<Array<domain.SetDraft>>;

export function NeedsReview():Promise<Array<domain.Track>>;

export function ProbeTidalCapabilities(arg1:string):Promise<tidal.CapabilityReport>;

export function PublishSet(arg1:string):Promise<spotify.Playlist>;

export function PublishTidalPreviews(arg1:Array<string>):Promise<tidal.PreviewBatch>;

export function SaveTidalSet(arg1:string):Promise<tidal.SavedSet>;

export function SaveTransitionFeedback(arg1:domain.TransitionFeedback):Promise<domain.TransitionFeedback>;

export function SeedReferenceCatalog():Promise<domain.Bootstrap>;

export function SpotifyConnected():Promise<boolean>;

export function SpotifyPlaylists():Promise<Array<spotify.Playlist>>;

export function SyncSpotifyPlaylists(arg1:Array<string>):Promise<domain.Bootstrap>;

export function TidalSavedSets():Promise<Array<tidal.SavedSet>>;

export function TidalStatus():Promise<tidal.Status>;

export function TrackWaveform(arg1:string):Promise<domain.TrackWaveform>;
