// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {spotify} from '../models';

export function Bootstrap():Promise<domain.Bootstrap>;

export function ConnectSpotify():Promise<void>;

export function EnrichTrack(arg1:domain.TrackEnrichment):Promise<void>;

export function GenerateSets(arg1:domain.GenerateRequest):Promise<Array<domain.SetDraft>>;

export function NeedsReview():Promise<Array<domain.Track>>;

export function PublishSet(arg1:string):Promise<spotify.Playlist>;

export function SeedReferenceCatalog():Promise<domain.Bootstrap>;

export function SpotifyConnected():Promise<boolean>;
