// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function ConnectSpotify() {
  return window['go']['main']['App']['ConnectSpotify']();
}

export function EnrichTrack(arg1) {
  return window['go']['main']['App']['EnrichTrack'](arg1);
}

export function GenerateSets(arg1) {
  return window['go']['main']['App']['GenerateSets'](arg1);
}

export function NeedsReview() {
  return window['go']['main']['App']['NeedsReview']();
}

export function PublishSet(arg1) {
  return window['go']['main']['App']['PublishSet'](arg1);
}

export function SeedReferenceCatalog() {
  return window['go']['main']['App']['SeedReferenceCatalog']();
}

export function SpotifyConnected() {
  return window['go']['main']['App']['SpotifyConnected']();
}

export function SpotifyPlaylists() {
  return window['go']['main']['App']['SpotifyPlaylists']();
}

export function SyncSpotifyPlaylists(arg1) {
  return window['go']['main']['App']['SyncSpotifyPlaylists'](arg1);
}
